# Requires repo secret: PERSONAL_ACCESS_TOKEN with permissions:
#   Administration: read and write

name: GitHub Repository Update

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  repo-update:
    permissions:
      repository-projects: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - run: |
          DATA=$(jq --raw-output --compact-output '{description: .description, homepage: .homepage}' package.json)
          gh api \
            --method PATCH \
            "repos/${GITHUB_REPOSITORY}" \
            --input <(echo "${DATA}")
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - run: |
          DATA=$(jq --raw-output --compact-output '{names: .keywords}' package.json)
          gh api \
            --method PUT \
            "repos/${GITHUB_REPOSITORY}/topics" \
            --input <(echo "${DATA}")
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
