name: Linter

on:
  pull_request:
    types:
      # - edited  # PR's base branch was changed
      - opened
      - reopened
      - synchronize  # PR's branch was edited (i.e. new commits)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  renovate-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rinchsan/renovate-config-validator@v0.2.0
        with:
          pattern: 'renovate.json5'

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: '.husky/*'

  workflow-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      # TODO(cemmer): re-enable when https://github.com/rhysd/actionlint/pull/392 releases
      # - run: actionlint

  # !!! This check should be required by GitHub !!!
  linter-status-check:
    if: always()
    needs:
      - renovate-lint
      - shellcheck
      - workflow-lint
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
