name: Pull Request Commenter

on:
  # pull_request_target required for pull-requests:write permission on fork PRs
  pull_request_target:
    types:
      # - edited  # PR's base branch was changed
      - opened
      - reopened
      - synchronize  # PR's branch was edited (i.e. new commits)
    paths:
      - '*'
      - 'src/**'
      - 'test/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  npm-exec-test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ ubuntu, macos, windows ]
    steps:
      - uses: actions/setup-node@v3
      - env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: npm exec --loglevel verbose --yes -- "github:${{ github.event.pull_request.head.repo.full_name }}#${HEAD_REF}" --help

  npm-exec:
    needs:
      - npm-exec-test
    runs-on: ubuntu-latest
    steps:
      - uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## :test_tube: Branch Testing
            This pull request can be tested locally with the following command:
            ```shell
            npm exec --yes -- "github:${{ github.event.pull_request.head.repo.full_name }}#${{ github.event.pull_request.head.ref }}" [commands..] [options]
            ```
            _Comment generated by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}) workflow._
          comment_tag: npm-exec
